(function(d){var f=document,n=d.location;if(!d.TJ58){d.TJ58=!0;null==d.String.prototype.trim&&(d.String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")});var e={curURL:n.href,referrer:f.referrer,protocol:n.protocol,window_size:f.documentElement.clientWidth+"x"+f.documentElement.clientHeight,screen_size:d.screen.width+","+d.screen.height,domain:function(){var b=n.host.toLowerCase(),a=/.*?([^\.]+\.(com|org|net|biz|edu|cc)(\.[^\.]+)?)/;return a.test(b)?"."+b.replace(a,
"$1"):""}(),navigation_type:function(){var b="-1";try{b=d.performance.navigation.type}catch(a){return"-1"}return b}(),setCookie:function(){if(!f.cookie)return!1;var b=new Date;2<arguments.length?b.setTime(b.getTime()+864E5*arguments[2]):b.setTime(b.getTime()+18E5);2<=arguments.length&&(f.cookie=arguments[0]+"="+escape(arguments[1])+"; expires="+b.toGMTString()+"; domain="+e.domain+"; path=/")},getCookie:function(b){if(!f.cookie)return"";var a;return(a=f.cookie.match(RegExp("(^| )"+b+"=([^;]*)(;|$)")))?
unescape(a[2]):""},ajaxsend:function(b){(new Image).src=b},getGTID:function(b,a,c){function e(a,b,c){a=(""+a).length<b?(Array(b+1).join("0")+a).slice(-b):""+a;return-1==c?a:a.substring(0,c)+"-"+a.substring(c)}var d={home:"1",index:"2",list:"3",detail:"4",post:"5",special:"6"};b=d[b]?parseInt(d[b]).toString(16):0;a=a.split(",");a=a[a.length-1];a=parseInt(a)?parseInt(a).toString(16):0;c=c.split(",");c=c[c.length-1];c=parseInt(c)?parseInt(c).toString(16):0;d=(13).toString(16);return"llpccccc-tttt-txxx-xxxx-xxxxxxxxxxxx".replace(/x/g,
function(a){return(16*Math.random()|0).toString(16)}).replace(/ccccc/,e(a,5,-1)).replace(/tttt-t/,e(c,5,4)).replace(/p/,e(b,1,-1)).replace(/ll/,e(d,2,-1))},setLocalStorage:function(b,a){try{d.localStorage&&d.localStorage.setItem(b,a)}catch(c){}},getLocalStorage:function(b){try{return d.localStorage?d.localStorage.getItem(b):""}catch(a){return""}},getUUID:function(b){var a="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*d.Math.random()|0;return("x"==a?b:b&3|8).toString(16)}),
a=this.getCookie(b)||this.getLocalStorage(b)||a;this.setCookie(b,a,365);this.setLocalStorage(b,a);return a},getRandom:function(){return d.Math.random()},bindElem:function(b,a,c,e,u){if(d.$&&"string"==typeof b&&"string"==typeof a&&"function"==typeof c)if("function"===typeof $(f).on)$(f).on(a,b,c);else"function"===typeof $(f).delegate?$(f).delegate(b,a,c):"function"===typeof $(b).bind&&$(b).bind(a,c)},loadScript:function(b,a){try{var c=f.createElement("script");c.type="text/javascript";c.readyState?
c.onreadystatechange=function(){if("loaded"==c.readyState||"complete"==c.readyState)c.onreadystatechange=null,a&&a()}:c.onload=function(){a&&a()};c.src=b;f.body.appendChild(c)}catch(e){}}},g={config:{trackLog:{server:"tracklog.58.com/pc/empty.js.gif",allParams:"site_name tag referrer post_count _trackParams userid smsc window_size _ga_utma trackURL rand_id".split(" "),uniqParams:["tag","rand_id"]},listShowLog:{server:"tracklog.58.com/PCv1/listshow/empty.js.gif",allParams:"tag bangbangid referrer site_name info_data trackURL rand_id".split(" "),
uniqParams:["tag","info_data","rand_id"]},listClickLog:{server:"tracklog.58.com/PCv1/listclick/empty.js.gif",allParams:"tag bangbangid referrer site_name info_data trackURL ClickID rand_id".split(" "),uniqParams:["tag","info_data","rand_id"]},clickLog:{server:"tracklog.58.com/pc/click/empty.js.gif",allParams:"site_name tag from trackURL ClickID bangbangid referrer rand".split(" "),uniqParams:["tag","from","rand"]},diaTrackLog:{server:"dialog.58.com/transfer",allParams:"DIATag tag referrer post_count _trackParams userid smsc window_size _ga_utma trackURL rand_id".split(" "),
uniqParams:["DIATag","tag","rand_id"]},diaClickLog:{server:"dialog.58.com/transfer",allParams:"DIATag from trackURL ClickID bangbangid referrer rand".split(" "),uniqParams:["DIATag","from","rand"]},diaShowLog:{server:"dialog.58.com/transfer",allParams:"DIATag trackURL ClickID bangbangid referrer rand".split(" "),uniqParams:["DIATag","rand"]},gdtTrackLog:{server:"gdt.cm.58.com/gdtcm",allParams:["city","cate","key","plat"],uniqParams:["city","key","plat"]},actionLog:{server:"tracklog.58.com/PCv1/action/empty.js.gif",
allParams:"site_name tag window_size action_data trackURL referrer rand_id".split(" "),uniqParams:["tag","action_data","rand_id"]}},filterList:function(b){var a=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com m.58.com/city.html lieche.m.58.com".split(" "),c;for(c in a)if(-1!==b.indexOf(a[c]))return"YES";return"NO"},getBaseInfo:function(){var b=d.site_name||"58",a=d.encodeURIComponent(e.referrer),c=e.curURL,B=e.getUUID("58tj_uuid"),u=e.getCookie("bangbangid"),
h=e.window_size,l=e.navigation_type,E=e.screen_size,m=d.____json4fe?d.____json4fe:{},f=m._trackPagetype||"",g=m._trackURL||"",k=m._trackParams||[],p=m.GA_pageview||"",n=m.infoid||"",M=m.userid||"",N=m.smsc||"",m=m.sid||"",v=d._trackURL||g||"NA",s={};try{s="NA"===v?{}:eval("("+v+")")}catch(R){s={}}var f=s.pagetype||f||d.page_type||"NA",g=s.post_count||d.post_count||-1,p=s.Ga_pageview||p||"",w=s.cate||"",O=""===w?"":w.split(",")[0],P=""===w&&-1===w.indexOf(",")?"":w.split(",")[1],F=s.area||"",K=""===
F?"":F.split(",")[0],L=e.getGTID(f,w,F),s=s.ROI||"",q=d._trackParams||k||[],x=[],k="";if(q instanceof Array){for(var k=0,I=q.length;k<I;k++)q[k]&&q[k].I&&q[k].V&&"string"===typeof q[k].V&&x.push(q[k].I+":"+q[k].V.replace(/\|/g,"*"));k=encodeURIComponent(x.join("@@"))}var x=(q=e.curURL.match(/[\?&]iuType=[a-z]*_[0-9]*/))?q[0].split("=")[1].split("_"):["",""],q=x[0],x=x[1],I=e.getCookie("als"),C=e.getCookie("utm_source"),Q=e.getCookie("utm_campaign"),D=e.getCookie("spm"),y,z,G;""!=e.getCookie("new_session")?
(y=e.getCookie("init_refer"),z="0"):(y=d.encodeURIComponent(e.referrer),z="1");G=""!=e.getCookie("new_uv")?parseInt(e.getCookie("new_uv"))+("0"==z?0:1):1;e.setCookie("new_session",z);e.setCookie("new_uv",G,365);var A=e.referrer.split("/")[2]||"",r=this.getValByUrl(e.curURL,"utm_source"),t=this.getValByUrl(e.curURL,"spm");e.referrer||"NA"==r&&"NA"==t?e.referrer||"NA"!=r||"NA"!=t||"1"!==z?A&&-1===A.indexOf(".58.com")&&-1===A.indexOf(".5858.com")&&-1===A.indexOf(".58cdn.com.cn")&&(y=d.encodeURIComponent(e.referrer),
C="NA"===r?"":r,D="NA"===t?"":t):D=C=y="":(y="",C="NA"===r?"":r,D="NA"===t?"":t);e.setCookie("utm_source",C);e.setCookie("spm",D);e.setCookie("init_refer",y);var A="1.1.1.1.1."+G,r=[],t=v.indexOf("{"),l={GTID:L,infoid:n,infotype:q,usertype:x,als:I,utm_source:C,utm_campaign:Q,spm:D,new_session:z,init_refer:y,new_uv:G,UUID:B,bangbangid:u,navtype:l,sc:E,sid:m},H;for(H in l)l.hasOwnProperty(H)&&r.push("'"+H+"':'"+l[H]+"'");r.join(",");v="NA"!==v&&-1!==t?v.substring(0,t+1)+r+","+v.substring(t+1):"{"+r+
"}";return{site_name:b,referrer:a,UUID:B,bangbangid:u,pagetype:f,post_count:g,cate:w,cate1:O,cate2:P,area:F,area1:K,city:K,GTID:L,ClickID:1,ROI:s,curURL:c,_trackParams:k,userid:M,smsc:N,window_size:h,trackURL:v,Ga_pageview:p,_ga_utma:A,ClickIDPlus:function(){this.ClickID+=1}}},getValByUrl:function(b,a){var c;c=b.match(RegExp("[&?]"+a+"=([^&|^#]*)"));return c instanceof Array?c[1]:"NA"},sendLog:function(b,a){var c=this.baseInfo,d=this.config[b];if(b&&d&&a&&"object"===typeof a){for(var f=[],h=d.allParams,
l=0,g=h.length;l<g;l++)f.push(h[l]+"="+(a[h[l]]||c[h[l]]||""));e.ajaxsend(e.protocol+"//"+d.server+"?"+f.join("&"))}},trackLog:function(){var b=this.baseInfo;this.sendLog("trackLog",{tag:"pvstatall",rand_id:e.getRandom()});if("list"===b.pagetype){var a=b.Ga_pageview.indexOf("?key="),a=-1!==a?b.Ga_pageview.substring(a+5):"";this.sendLog("gdtTrackLog",{city:b.area,key:a,plat:"PC"})}},clickLog:function(b){var a="",a=null!=b&&"from="===b.substring(0,5)?b.replace("from=",""):"default&"+b;this.sendLog("clickLog",
{tag:"pvsiters",from:a,rand:e.getRandom()});setTimeout("GCIDPlus()",300)},listClickLog:function(){var b=this,a=this.baseInfo;if(d.$&&"NA"!==a.pagetype&&"NA"!==a.trackURL){var c={list:1,jianli_list:1,xiaoqu:1,qijiandian:1,item:1,xinchong:1},f=function(){if("function"==typeof $(this).parents){var c="",c=$(this).parents("[logr]"),d=[],f="",g=c.attr("logr").split("_"),u=c.attr("_pos"),B=c.attr("sortid"),k=c.attr("infoproperty"),p=g[g.length-1];d.push(g[0],g[1],g[2],g[3]);p&&(p=p.replace("ses^","ses:"),
f+=p);p="";p="function"==typeof $("[logr]").index?$("[logr]").index(c)+1:c.attr("pos");f=f+(B?"@sortid:"+B:"")+(p?"@pos:"+p:"");f+=u?"@npos:"+u:"";f+=k?"@infoproperty:"+k:"";""!=f&&(0===f.indexOf("@")&&(f=f.substring(1)),d.push(f));c=d.join("_");"NO"==b.filterList(a.curURL)&&-1!=a.curURL.indexOf(".58.com")&&(d=$(this).attr("href")||"#",-1!=d.indexOf("javascript:")||"#"==d.substring(0,1)||"NO"!=b.filterList(d)||"/"!=d.substring(0,1)&&-1==d.indexOf(".58.com")||d.match(/[\?&]iuType=/)||$(this).attr("href",
d.trim()+(-1==d.indexOf("?")?"?":"&")+"iuType="+g[0]+"_"+g[1]));b.sendLog("listClickLog",{tag:"pclistclick",info_data:c,rand_id:e.getRandom()});setTimeout("GCIDPlus()",300)}},g=$("[tongji_label=listclick]");g&&0<g.length?$("[logr] [tongji_label=listclick]").bind("click",f):1===c[a.pagetype]?($("[logr] a.t").bind("click",f),"12"===a.cate2?($("[logr] a.jjh_img").bind("click",f),$("[logr] .img a").bind("click",f)):"187"===a.cate1||"42270"===a.cate1?$("[logr]").find("a:first").bind("click",f):"9225"===
a.cate1||"13952"===a.cate1?$("[logr] a.fl").bind("click",f):$("[logr] .img a").bind("click",f)):"chexing"===a.pagetype&&($("[logr] a.at").bind("click",f),$("[logr] .tdimg a").bind("click",f))}},listShowLog:function(){var b=this.baseInfo;if(d.$&&"list"===b.pagetype){for(var b=[],a=$("[logr]"),c=0,f=a.length;c<f;c++)if($(a[c]).attr("logr")&&"function"==typeof $(a[c]).attr){var g=[],h="",l=$(a[c]).attr("logr").split("_"),E=$(a[c]).attr("_pos"),m=c+1,n=$(a[c]).attr("sortid"),J=$(a[c]).attr("infoproperty"),
k=l[l.length-1];g.push(l[0],l[1],l[2],l[3]);k&&(k=k.replace("ses^","ses:"),h+=k);h+=n?"@sortid:"+n:"";h+=m?"@pos:"+m:"";h+=E?"@npos:"+E:"";h+=J?"@infoproperty:"+J:"";""!=h&&(0===h.indexOf("@")&&(h=h.substring(1)),g.push(h));b.push(g.join("_"))}this.sendLog("listShowLog",{tag:"pclistshow",info_data:b.join(","),rand_id:e.getRandom()})}},bindTongji_tag:function(){if(d.$){var b=this;e.bindElem("[tongji_tag]","click",function(){var a=$(this).attr("tongji_tag"),c=$(this).text().trim();b.clickLog("from="+
a+"&text="+encodeURIComponent(c)+"&tongji_type=tongji_tag")},b)}},bindTongji_id:function(){if(d.$){var b=this;e.bindElem("[tongji_id]","click",function(a){var c=a.srcElement?a.srcElement:a.target;"A"==c.tagName.toUpperCase()&&(a=$(c).attr("href")||"#",c=$(c).text(),-1==a.indexOf("javascript:")&&"#"!=a.substring(0,1)&&b.clickLog("from="+$(this).attr("tongji_id")+"&text="+encodeURIComponent(c)+"&to="+encodeURIComponent(a)+"&tongji_type=tongji_id"))},b)}},diaShowLog:function(b){},bindAlsTag:function(){if(!e.getCookie("als")&&
d.$&&"function"===typeof $("body").one)$("body").one("mouseover",function(){e.setCookie("als","0",365)});e.getCookie("isSpider")&&e.setCookie("isSpider","",0)},bindHomeHeatMap:function(){var b=this,a=this.baseInfo;d.$&&"home"===a.pagetype&&e.bindElem("[href]","click",function(a){var d=$(this).attr("href"),e=$(this).text().trim(),f=$(this).attr("tongji_tag")||"NA",g=$(this).offset().top,n=$(this).offset().left,m=a.pageX;a=a.pageY;b.clickLog("from=heatmap:"+encodeURIComponent(d)+"&tagX="+n+"&tagY="+
g+"&mouseX="+m+"&mouseY="+a+"&text="+encodeURIComponent(e)+"&tongji_tag="+f)},b)},insertMiGuan:function(){try{var b="default";switch(this.baseInfo.cate1){case "9224":case "9225":case "13941":case "13952":b="yewu";break;case "1":b="ershoufang";break;case "5":b="shouji";break;case "832":b="dog";break;case "4":b="ershouche";break;default:b="shenghuo"}var a=Math.ceil(1E14*Math.random()),c=document.getElementsByTagName("body")[0],d=document.createElement("div");d.id="addInfo";d.style.display="none";var f=
document.createElement("a");f.href=e.protocol+"//tracklog.58.com/detail/pc/"+b+"/"+a+"x.shtml";f.text="\u63a8\u8350\u4fe1\u606f";d.appendChild(f);c.appendChild(d)}catch(g){}},bindAddGTIDtoURL:function(){var b=this,a=this.baseInfo;d.$&&e.bindElem("a","click",function(c){"NO"==b.filterList(a.curURL)&&-1!=a.curURL.indexOf(".58.com")&&(c=$(this).attr("href")||"#",-1!=c.indexOf("javascript:")||"#"==c.substring(0,1)||"NO"!=b.filterList(c)||"/"!=c.substring(0,1)&&-1==c.indexOf(".58.com")||(c.match(/[\?&]ClickID=\d*/)?
$(this).attr("href",c.replace(/ClickID=\d*/,"ClickID="+a.ClickID)):$(this).attr("href",c.trim()+(-1==c.indexOf("?")?"?":"&")+"PGTID="+a.GTID+"&ClickID="+a.ClickID)))},b,a)},ActionObj:{data:[]},actionFilter:function(){pagetypeArr=["home","index","list","jianli_index","jianli_list"];var b=this.baseInfo,a=!1,c;for(c in pagetypeArr)if(b.pagetype==pagetypeArr[c]){a=!0;break}return a?!0:!1},actionLog:function(){var b=this;b.actionFilter()&&(e.bindElem("body","click",function(a){var c=b.ActionObj.data,n=
f.body.scrollWidth||"",u=f.body.scrollHeight||"";a=a||d.event;var h=f.documentElement.scrollLeft||f.body.scrollLeft,l=f.documentElement.scrollTop||f.body.scrollTop,h=a.pageX||a.clientX+h||"-1";a=a.pageY||a.clientY+l||"-1";h=Math.floor(h);a=Math.floor(a);c.push("CLICK_"+n+"_"+u+"_"+h+"_"+a);c instanceof Array&&5<=c.length&&(c=c.join(","),g.ActionObj.data=[],b.sendLog("actionLog",{tag:"pcaction",action_data:c,rand_id:e.getRandom()}))}),$(d).unload(function(){var a=b.ActionObj;(a=a?a.data:"")&&a instanceof
Array&&0<a.length&&(a=a.join(","),g.ActionObj.data=[],b.sendLog("actionLog",{tag:"pcaction",action_data:a,rand_id:e.getRandom()}))}))},DMloadByTag:function(){try{var b=this.getValByUrl(e.curURL,"dm-statistic-detect"),a=e.getCookie("dm-statistic-detect");if(b=("NA"==b?"":b)||a||"")switch(d.TJ58ecdata={},d.TJ58ecdata.platform="58PC",b){case "2":e.loadScript("http://bigdata.web.58dns.org/stat/static/js/referrer_alert.js");break;case "3":e.loadScript("http://bigdata.web.58dns.org/stat/static/js/referrer_visual.js")}}catch(c){}}};
g.baseInfo=g.getBaseInfo();g.trackLog();g.listShowLog();g.listClickLog();g.bindAlsTag();g.bindTongji_tag();g.bindTongji_id();g.bindHomeHeatMap();g.bindAddGTIDtoURL();g.insertMiGuan();g.actionLog();d.clickLog=function(b){g.clickLog(b)};d.showLog=function(b){g.diaShowLog(b)};d.GCIDPlus=function(){g.baseInfo.ClickIDPlus()};d.ajaxlogr=function(b){};d.getGTID=function(){return g.baseInfo.GTID};d._gaq=d._gaq||[];g.DMloadByTag()}})(window);
